apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: first-task
spec:
  params:
  resources:
  steps:
    - name: first-task
      image: python      
      script: |
        #!/usr/bin/env python3
        echo $sample_python.py
